openapi: 3.0.0
info:
  title: notification
  version: '1.0'
  description: Notifications api
  contact:
    name: Daniel Rodriguez
    email: eduardo.rodriguezg@axity.com
servers:
  - url: 'http://localhost:8080'
    description: 'LocalHost:8080'
paths:
  /push:
    get:
      summary: Get Notifications
      tags: []
      description: Get notifications
      operationId: '1'
  /login:
    get:
      summary: get_token
      tags: []
      responses:
        '200':
          description: OK
      description: ''
components:
  schemas: {}
